# Configuración de la fuente
[font]
size = 9

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

# Configuración de la ventana
[window]
opacity = 0.8

# Configuración de los colores
[colors.primary]
background = "#23120f"
foreground = "#c8c3c3"

[colors.cursor]
cursor = "#c8c3c3"
text = "CellForeground"

[colors.normal]
black = "#74605e"
red = "#2E518D"
green = "#5F699F"
yellow = "#A87394"
blue = "#7486BB"
magenta = "#A791A6"
cyan = "#DEA7A8"
white = "#c8c3c3"

[colors.bright]
black = "#23120f"
red = "#2E518D"
green = "#5F699F"
yellow = "#A87394"
blue = "#7486BB"
magenta = "#A791A6"
cyan = "#DEA7A8"
white = "#c8c3c3"

# Configuración de los atajos de teclado
[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

# Configuración de los atajos del mouse
[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"
