# Configuración de la fuente
[font]
size = 9

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

# Configuración de la ventana
[window]
opacity = 0.8

# Configuración de los colores
[colors.primary]
background = "#090e06"
foreground = "#c1c2c0"

[colors.cursor]
cursor = "#c1c2c0"
text = "CellForeground"

[colors.normal]
black = "#5d6955"
red = "#3B5242"
green = "#5B6951"
yellow = "#6A8F5F"
blue = "#8B9772"
magenta = "#7A9383"
cyan = "#9FAC99"
white = "#c1c2c0"

[colors.bright]
black = "#090e06"
red = "#3B5242"
green = "#5B6951"
yellow = "#6A8F5F"
blue = "#8B9772"
magenta = "#7A9383"
cyan = "#9FAC99"
white = "#c1c2c0"

# Configuración de los atajos de teclado
[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

# Configuración de los atajos del mouse
[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"
